#!/usr/bin/env perl

use strict;
use warnings;

#open(my $controller, "|../Pipes/controller") || die "Can't fork: $!";
open(my $controller, "|./controller/controller-automated") || die "Can't fork: $!";
open(my $sound, "|./audio/audio audio") || die "Can't fork: $!";
open(STDOUT, ">&", $controller);
open(STDERR, ">&", $sound);

exec "./video/video";
